// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Agenda documents */
interface AgendaDocumentData {
    /**
     * Title field in *Agenda*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: agenda.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Waktu field in *Agenda*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: agenda.waktu
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    waktu: prismicT.KeyTextField;
    /**
     * Tempat field in *Agenda*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: agenda.tempat
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    tempat: prismicT.KeyTextField;
    /**
     * Tanggal field in *Agenda*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: agenda.tanggal
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    tanggal: prismicT.DateField;
}
/**
 * Agenda document from Prismic
 *
 * - **API ID**: `agenda`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AgendaDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<AgendaDocumentData>, "agenda", Lang>;
/** Content for Berita documents */
interface BeritaDocumentData {
    /**
     * Layout field in *Berita*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: berita.layout
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    layout: prismicT.RelationField<"layouts">;
    /**
     * Title field in *Berita*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Judul berita
     * - **API ID Path**: berita.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Description field in *Berita*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Deskripsi berita
     * - **API ID Path**: berita.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Date field in *Berita*
     *
     * - **Field Type**: Date
     * - **Placeholder**: Tanggal berita dibuat
     * - **API ID Path**: berita.date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    date: prismicT.DateField;
    /**
     * Image field in *Berita*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: berita.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *Berita*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: berita.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<BeritaDocumentDataSlicesSlice>;
}
/**
 * Slice for *Berita → Slice Zone*
 *
 */
type BeritaDocumentDataSlicesSlice = ParagraphSlice | ImageSlice;
/**
 * Berita document from Prismic
 *
 * - **API ID**: `berita`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BeritaDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<BeritaDocumentData>, "berita", Lang>;
/** Content for Gallery documents */
interface GalleryDocumentData {
    /**
     * Title field in *Gallery*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Description field in *Gallery*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *Gallery*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery.image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * Date field in *Gallery*
     *
     * - **Field Type**: Date
     * - **Placeholder**: *None*
     * - **API ID Path**: gallery.date
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/date
     *
     */
    date: prismicT.DateField;
}
/**
 * Gallery document from Prismic
 *
 * - **API ID**: `gallery`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<GalleryDocumentData>, "gallery", Lang>;
/** Content for Layouts documents */
interface LayoutsDocumentData {
    /**
     * Slice Zone field in *Layouts*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: layouts.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<LayoutsDocumentDataSlicesSlice>;
}
/**
 * Slice for *Layouts → Slice Zone*
 *
 */
type LayoutsDocumentDataSlicesSlice = FooterMainSlice | NavbarMainSlice | ChildrenSlice;
/**
 * Layouts document from Prismic
 *
 * - **API ID**: `layouts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<LayoutsDocumentData>, "layouts", Lang>;
/** Content for Pages documents */
interface PagesDocumentData {
    /**
     * Html Title field in *Pages*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pages.htmlTitle
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    htmlTitle: prismicT.KeyTextField;
    /**
     * Route field in *Pages*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: pages.route
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    route: prismicT.KeyTextField;
    /**
     * Layout field in *Pages*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: pages.layout
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    layout: prismicT.RelationField<"layouts">;
    /**
     * Slice Zone field in *Pages*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: pages.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PagesDocumentDataSlicesSlice>;
}
/**
 * Slice for *Pages → Slice Zone*
 *
 */
type PagesDocumentDataSlicesSlice = BannerSlice | BeritaOverviewSlice | TentangSlice;
/**
 * Pages document from Prismic
 *
 * - **API ID**: `pages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PagesDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PagesDocumentData>, "pages", Lang>;
/** Content for Redirect Link documents */
interface RedirectLinkDocumentData {
    /**
     * route field in *Redirect Link*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: redirect_link.route
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    route: prismicT.KeyTextField;
}
/**
 * Redirect Link document from Prismic
 *
 * - **API ID**: `redirect_link`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RedirectLinkDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<RedirectLinkDocumentData>, "redirect_link", Lang>;
export type AllDocumentTypes = AgendaDocument | BeritaDocument | GalleryDocument | LayoutsDocument | PagesDocument | RedirectLinkDocument;
/**
 * Item in Banner → Items
 *
 */
export interface BannerSliceDefaultItem {
    /**
     * image field in *Banner → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.items[].image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
    /**
     * text field in *Banner → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
    /**
     * button field in *Banner → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.items[].button
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    button: prismicT.KeyTextField;
    /**
     * href field in *Banner → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: banner.items[].href
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    href: prismicT.KeyTextField;
}
/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Banner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<BannerSliceDefaultItem>>;
/**
 * Slice variation for *Banner*
 *
 */
type BannerSliceVariation = BannerSliceDefault;
/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: `Banner`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BannerSlice = prismicT.SharedSlice<"banner", BannerSliceVariation>;
/**
 * Default variation for BeritaOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: `BeritaOverview`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BeritaOverviewSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Slice variation for *BeritaOverview*
 *
 */
type BeritaOverviewSliceVariation = BeritaOverviewSliceDefault;
/**
 * BeritaOverview Shared Slice
 *
 * - **API ID**: `berita_overview`
 * - **Description**: `BeritaOverview`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BeritaOverviewSlice = prismicT.SharedSlice<"berita_overview", BeritaOverviewSliceVariation>;
/**
 * Default variation for Children Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Children`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ChildrenSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Slice variation for *Children*
 *
 */
type ChildrenSliceVariation = ChildrenSliceDefault;
/**
 * Children Shared Slice
 *
 * - **API ID**: `children`
 * - **Description**: `Children`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ChildrenSlice = prismicT.SharedSlice<"children", ChildrenSliceVariation>;
/**
 * Primary content in FooterMain → Primary
 *
 */
interface FooterMainSliceDefaultPrimary {
    /**
     * Logo field in *FooterMain → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_main.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
    /**
     * address field in *FooterMain → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_main.primary.address
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    address: prismicT.RichTextField;
}
/**
 * Item in FooterMain → Items
 *
 */
export interface FooterMainSliceDefaultItem {
    /**
     * Text field in *FooterMain → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_main.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    text: prismicT.KeyTextField;
    /**
     * link field in *FooterMain → Items*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: footer_main.items[].link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
}
/**
 * Default variation for FooterMain Slice
 *
 * - **API ID**: `default`
 * - **Description**: `FooterMain`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterMainSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FooterMainSliceDefaultPrimary>, Simplify<FooterMainSliceDefaultItem>>;
/**
 * Slice variation for *FooterMain*
 *
 */
type FooterMainSliceVariation = FooterMainSliceDefault;
/**
 * FooterMain Shared Slice
 *
 * - **API ID**: `footer_main`
 * - **Description**: `FooterMain`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterMainSlice = prismicT.SharedSlice<"footer_main", FooterMainSliceVariation>;
/**
 * Primary content in Image → Primary
 *
 */
interface ImageSliceDefaultPrimary {
    /**
     * Title field in *Image → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: image.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Image field in *Image → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Image*
 *
 */
type ImageSliceVariation = ImageSliceDefault;
/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSlice = prismicT.SharedSlice<"image", ImageSliceVariation>;
/**
 * Primary content in NavbarMain → Primary
 *
 */
interface NavbarMainSliceDefaultPrimary {
    /**
     * Logo field in *NavbarMain → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navbar_main.primary.logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
}
/**
 * Item in NavbarMain → Items
 *
 */
export interface NavbarMainSliceDefaultItem {
    /**
     * text field in *NavbarMain → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navbar_main.items[].text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    text: prismicT.KeyTextField;
    /**
     * route field in *NavbarMain → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navbar_main.items[].route
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    route: prismicT.KeyTextField;
}
/**
 * Default variation for NavbarMain Slice
 *
 * - **API ID**: `default`
 * - **Description**: `NavbarMain`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavbarMainSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<NavbarMainSliceDefaultPrimary>, Simplify<NavbarMainSliceDefaultItem>>;
/**
 * Slice variation for *NavbarMain*
 *
 */
type NavbarMainSliceVariation = NavbarMainSliceDefault;
/**
 * NavbarMain Shared Slice
 *
 * - **API ID**: `navbar_main`
 * - **Description**: `NavbarMain`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NavbarMainSlice = prismicT.SharedSlice<"navbar_main", NavbarMainSliceVariation>;
/**
 * Primary content in Paragraph → Primary
 *
 */
interface ParagraphSliceDefaultPrimary {
    /**
     * Text field in *Paragraph → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: paragraph.primary.text
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    text: prismicT.RichTextField;
}
/**
 * Default variation for Paragraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Paragraph`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ParagraphSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ParagraphSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Paragraph*
 *
 */
type ParagraphSliceVariation = ParagraphSliceDefault;
/**
 * Paragraph Shared Slice
 *
 * - **API ID**: `paragraph`
 * - **Description**: `Paragraph`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ParagraphSlice = prismicT.SharedSlice<"paragraph", ParagraphSliceVariation>;
/**
 * Primary content in Tentang → Primary
 *
 */
interface TentangSliceDefaultPrimary {
    /**
     * Title field in *Tentang → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: tentang.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Description field in *Tentang → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: tentang.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
    /**
     * Image field in *Tentang → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: tentang.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for Tentang Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Tentang`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TentangSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TentangSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Tentang*
 *
 */
type TentangSliceVariation = TentangSliceDefault;
/**
 * Tentang Shared Slice
 *
 * - **API ID**: `tentang`
 * - **Description**: `Tentang`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TentangSlice = prismicT.SharedSlice<"tentang", TentangSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { AgendaDocumentData, AgendaDocument, BeritaDocumentData, BeritaDocumentDataSlicesSlice, BeritaDocument, GalleryDocumentData, GalleryDocument, LayoutsDocumentData, LayoutsDocumentDataSlicesSlice, LayoutsDocument, PagesDocumentData, PagesDocumentDataSlicesSlice, PagesDocument, RedirectLinkDocumentData, RedirectLinkDocument, AllDocumentTypes, BannerSliceDefaultItem, BannerSliceDefault, BannerSliceVariation, BannerSlice, BeritaOverviewSliceDefault, BeritaOverviewSliceVariation, BeritaOverviewSlice, ChildrenSliceDefault, ChildrenSliceVariation, ChildrenSlice, FooterMainSliceDefaultPrimary, FooterMainSliceDefaultItem, FooterMainSliceDefault, FooterMainSliceVariation, FooterMainSlice, ImageSliceDefaultPrimary, ImageSliceDefault, ImageSliceVariation, ImageSlice, NavbarMainSliceDefaultPrimary, NavbarMainSliceDefaultItem, NavbarMainSliceDefault, NavbarMainSliceVariation, NavbarMainSlice, ParagraphSliceDefaultPrimary, ParagraphSliceDefault, ParagraphSliceVariation, ParagraphSlice, TentangSliceDefaultPrimary, TentangSliceDefault, TentangSliceVariation, TentangSlice };
    }
}
