// Code generated by Slice Machine. DO NOT EDIT.

import Banner from './Banner';
import BeritaOverview from './BeritaOverview';
import Children from './Children';
import FooterMain from './FooterMain';
import Header from './Header';
import Image from './Image';
import NavbarMain from './NavbarMain';
import Paragraph from './Paragraph';
import Tentang from './Tentang';

export {
	Banner,
	BeritaOverview,
	Children,
	FooterMain,
	Header,
	Image,
	NavbarMain,
	Paragraph,
	Tentang
};

export const components = {
	banner: Banner,
	berita_overview: BeritaOverview,
	children: Children,
	footer_main: FooterMain,
	header: Header,
	image: Image,
	navbar_main: NavbarMain,
	paragraph: Paragraph,
	tentang: Tentang
};

