// Code generated by Slice Machine. DO NOT EDIT.

import Banner from './Banner';
import Children from './Children';
import FooterMain from './FooterMain';
import Image from './Image';
import NavbarMain from './NavbarMain';
import Paragraph from './Paragraph';

export {
	Banner,
	Children,
	FooterMain,
	Image,
	NavbarMain,
	Paragraph,
};

export const components = {
	banner: Banner,
	children: Children,
	footer_main: FooterMain,
	image: Image,
	navbar_main: NavbarMain,
	paragraph: Paragraph,
};
